FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y curl && \
    mkdir /odoko && \
    cd /usr/local && \
    curl https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz | tar -xz 

ENV GOPATH=/odoko/golibs
ENV PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

WORKDIR /odoko
ADD /src /odoko/golibs/src/
ADD build.sh /odoko

ENTRYPOINT ["./build.sh"]
